image: python:latest

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - pip install flake8
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pip install pylint
  - pylint -d C0301 bild/*.py

pytest:
  stage: Test
  script:
  - pip install pytest
  - pip install .
  - cd tests/; pytest -v
